export const COLORS = Object.freeze({
  bg: "#fff",
  flowbg: "#f2f2f2",
  font: "#2a2929",
  bgHandle: "#cdcdcd",
  leadUserIcon: "#f05494",
  leadUserBg: "#fbd6e5",
  leadUserBorder: "#f773aa",
  sourceBg: "#e3cbfb",
  sourceIcon: "#9a51af",
  sourceBorder: "#ccaee4",
  conditionBg: "#eaf1f7",
  conditionIcon: "#1fa9f8",
  conditionBorder: "#97cef4",
});
